
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/url;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    properties:
      hibernate.format_sql: true